### PR TITLE
OSX packaging

### PR DESCRIPTION
**Pull request by inglesp**
This *should* allow us to build a mu package on OSX.

### CODE REVIEW

**Comment by carlosperate** [comment]
Looks like you might have to pip install with sudo https://travis-ci.org/ntoll/mu/jobs/101403831#L3296
Which would also answer the question you had in https://github.com/ntoll/mu/pull/43 about `sudo pip3 install --upgrade pip setuptools`.

**Comment by inglesp** [comment]
Well, looks like this might've worked.  We won't know though until we try to run the built package -- is there any way to get hold of that?

**Comment by carlosperate** [comment]
you can specify deployment all all branches (https://docs.travis-ci.com/user/deployment/) to get the built file uploaded to the aws s3 bucket.

**Comment by ntoll** [comment]
I'm happy to merge this once I have seen it working on my wife's OSX MacBook ;-)

I'll create a new issue to add details of the build process to the project README - this is important since people need to know where to get the binaries for their respective platforms.

**Comment by ntoll** [comment]
So the builds will (hopefully) end up here:

http://ardublockly-builds.s3-website-us-west-2.amazonaws.com/?prefix=microbit/

I'll merge to kick the build off and let's see what the OSX package looks like.

**Comment by carlosperate** [comment]
I cannot really test in OS X until later in the day, but the images deployed to http://ardublockly-builds.s3-website-us-west-2.amazonaws.com/?prefix=microbit/osx/ seem too small to possibly be correct?

**Comment by ntoll** [comment]
Correct... @inglesp has already had a look into this and will fix this evening.

**Comment by carlosperate** [comment]
:+1:

**Pull request merged**
