### PR TITLE
Adding python module packages to deb dependencies

### PR DESCRIPTION
**Pull request by carlosperate**
Changes made to the deb control file to add the python module packages.

We shouldn't use a post script to "pip install" the modules required, as that would go against the general philosophy of using the OS packaging system. So the modules have to be installed as packages, just as we've been doing with PyQt5.

In this case these are the modules we needed:

pyserial -> [python3-serial](http://packages.ubuntu.com/trusty/python-serial)
pyflakes -> [python3-flake8](http://packages.ubuntu.com/trusty/python3-flake8) 
pycodestyle -> [python3-pep8](http://packages.ubuntu.com/trusty/python3-pep8)

As you can see we are installing the old pep8 named packaged instead of pycodestyle. As this was quite recent rename there is currently no new packages available, so I had to add a `try/except ImportError` to import with one name or the other. Hopefully it will not be that long before it is added and we can revert that to a single line import: https://osdir.com/ml/debian-python/2016-06/msg00041.html

We still need to test this in a Raspberry Pi to see if the packages are also available there.

### CODE REVIEW

**Comment by carlosperate** [comment]
Based on the list provided in http://archive.raspberrypi.org/debian/dists/jessie/main/binary-armhf/Packages it looks like python3-flake8, nor any package for pep8 or pyflakes is available.

@asb @bennuttall would you be able to guide us to figure out what we would need to do to get these packages into raspbian?

**Comment by RogueM** [comment]
both python3-pep8 and python3-flake8 are available in the Raspbian Jessie repo at this stage so that shouldn't cause any problem.

and, fyi, python3-serial is currently rolling out version 2.6.0

**Comment by carlosperate** [comment]
@RogueM have you been able to install those packages in a clean installation of raspbian?

**Comment by RogueM** [comment]
yes, absolutely, I did it just before my last post to be sure the info had weight.

**Comment by carlosperate** [comment]
That's great news then.
If you could also test https://s3-us-west-2.amazonaws.com/ardublockly-builds/microbit/raspberry_pi/mu-2016-07-29_23_01_16.deb on a clean installation it would also help us to dot the i's and cross the t's.

**Comment by RogueM** [comment]
`pi@raspberrypi:~ $ sudo dpkg -i ./mu-2016-07-29_23_01_16.deb
Selecting previously unselected package mu.
(Reading database ... 118612 files and directories currently installed.)
Preparing to unpack ./mu-2016-07-29_23_01_16.deb ...
Unpacking mu (0.1-1) ...
Setting up mu (0.1-1) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...`

this is after running:

`sudo apt-get install python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtserialport python3-pep8 pyflakes`

**Comment by carlosperate** [comment]
Thanks a lot @RogueM, I assume the application was installed correctly and runs as expected?
The general idea of the deb package is that all the packages you've mentioned should have been installed automatically from the deb installation without having to `apt-get install` them. Did the installation fail before you tried `apt-get install`?

At the moment this deb installs `python-flake8` instead of `pyflakes`, but from your previous post it sounds like both packages are available.

**Comment by bennuttall** [comment]
Sorry I've been on holiday, just catching up. @xecdesign can probably point you in the right direction as to how to submit the packages.

**Comment by RogueM** [comment]
@carlosperate sorry, I used dkpg, apt-get won't work unless the package is in the repo, or is there a way to use a local file without messing with the source list?

basically, the packages I install manually are the dependencies dpkg told me were missing on a first try, so I suspect those are what packages would have been pulled automatically.

... anyhow, happy to run some tests in a way that answers your question more precisely or meaningfully, but you'll have to give me a rundown of the exact process you want me to follow.

**Comment by RogueM** [comment]
and to answer your question, I did not try to flash a micro-bit, but Mu launched fine from LXDE menu entry in Raspbian, including facility to code check, at a glance.

I can try flashing my micro-bit later tonight if you want, but I suspect that has not much relevance to the packages you are trying to introduce into the deb control file?

**Comment by RogueM** [comment]
here is the output received when trying to `dpkg -I` the deb:

```
pi@raspberrypi:~ $ sudo dpkg -i ./mu-2016-07-29_23_01_16.deb
Selecting previously unselected package mu.
(Reading database ... 118457 files and directories currently installed.)
Preparing to unpack ./mu-2016-07-29_23_01_16.deb ...
Unpacking mu (0.1-1) ...
dpkg: dependency problems prevent configuration of mu:
 mu depends on python3-pyqt5; however:
  Package python3-pyqt5 is not installed.
 mu depends on python3-pyqt5.qsci; however:
  Package python3-pyqt5.qsci is not installed.
 mu depends on python3-pyqt5.qtserialport; however:
  Package python3-pyqt5.qtserialport is not installed.
 mu depends on python3-pep8; however:
  Package python3-pep8 is not installed.
 mu depends on pyflakes; however:
  Package pyflakes is not installed.

dpkg: error processing package mu (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing: mu
```

I will try to gdebi, which seems to be able to manage dependencies over apt when dealing with a deb, but at that point it will no longer be running your package on a vanilla Raspbian as it's not installed by default... not that it matters in my view but that's the best method I can think of for simulating your package being in the repo in place of the current mu deb version.

**Comment by RogueM** [comment]
regarding python-flake8 vs pyflakes, here's what apt wants to pull when I try python-flake8:

```
pi@raspberrypi:~ $ sudo apt-get install python-flake8
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  pep8 pyflakes python-mccabe
Suggested packages:
  python-mock
The following NEW packages will be installed:
  pep8 pyflakes python-flake8 python-mccabe
0 upgraded, 4 newly installed, 0 to remove and 63 not upgraded.
Need to get 98.2 kB of archives.
After this operation, 690 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

... so it seems that python-flake8 was declared to depend on pyflakes itself. This is confirmed in the following output:

```
pi@raspberrypi:~ $ sudo apt-cache show python-flake8
Package: python-flake8
Version: 2.2.2-1
Installed-Size: 105
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: all
Depends: pep8 (>= 1.5.7), pyflakes (>= 0.8.1), python-mccabe (>= 0.2.1), python (>= 2.7), python (<< 2.8)
Suggests: python-mock
Size: 18976
SHA256: 18de5931999eb1bbd73454c757020e2bb7b6257bff16acfd7edb22dff33fed9f
SHA1: 7fe1d6890173636a7f6466a189a5b2cb411b1bca
MD5sum: 7705e0a5770ca0dbb1f98e00e4ce5d27
Description: code checker using pep8 and pyflakes
 Flake8 is a wrapper around PyFlakes, pep8, and Ned's McCabe script. Flake8
 runs all tools by launching the single 'flake8' script, but ignores pep8 and
 PyFlakes extended options and just uses defaults. It displays the warnings in
 a per-file, merged output.
 .
 This package provides Python 2 module bindings only.
Description-md5: 99e1b0956db1b675c8b696032f892766
Homepage: http://bitbucket.org/tarek/flake8
Section: python
Priority: optional
Filename: pool/main/p/python-flake8/python-flake8_2.2.2-1_all.deb

```

... I hope this helps but let me know if you'd like me to try anything else.

**Comment by RogueM** [comment]
and I can now confirm gdebi allowed your package to install without issue. That said, the mu-2016-07-29_23_01_16.deb control file definitely specifies pyflakes and not python-flake8. Both would be honoured on the latest Raspbian Jessie though, but I'm confused by your earlier question, did you mean the opposite of what you posted?

**Comment by RogueM** [comment]
and the following seems to work:

- flashing
- code check
- code completion

**Comment by XECDesign** [comment]
Instead of using gdebi or installing dependencies manually, you can run `apt-get install -f` after installing the package with `dpkg -i blah.deb`.

I think `python3-pkg-resources` is missing from dependencies.

Unrelated issue, but to avoid leaving cruft behind when uninstalling, it might make sense to move the udev rules file to the/ lib path instead of /etc.

**Comment by RogueM** [comment]
sure, I can't see why that wouldn't work, but I'll post the output if that helps.

btw, looking at the PR, I see it is introducing python-flake8, should't that be python3-flake8?

**Comment by RogueM** [comment]
```
pi@raspberrypi:~ $ sudo dpkg -i ./mu-2016-07-29_23_01_16.deb
Selecting previously unselected package mu.
(Reading database ... 118080 files and directories currently installed.)
Preparing to unpack ./mu-2016-07-29_23_01_16.deb ...
Unpacking mu (0.1-1) ...
dpkg: dependency problems prevent configuration of mu:
 mu depends on python3-pyqt5; however:
  Package python3-pyqt5 is not installed.
 mu depends on python3-pyqt5.qsci; however:
  Package python3-pyqt5.qsci is not installed.
 mu depends on python3-pyqt5.qtserialport; however:
  Package python3-pyqt5.qtserialport is not installed.
 mu depends on python3-pep8; however:
  Package python3-pep8 is not installed.
 mu depends on pyflakes; however:
  Package pyflakes is not installed.

dpkg: error processing package mu (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing: mu  

pi@raspberrypi:~ $ sudo apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libqt5clucene5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5gui5
  libqt5help5 libqt5network5 libqt5printsupport5 libqt5scintilla2-11
  libqt5scintilla2-l10n libqt5serialport5 libqt5sql5 libqt5sql5-sqlite
  libqt5test5 libqt5widgets5 libqt5xml5 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1
  libxkbcommon-x11-0 mu python3-pyqt5 python3-pyqt5.qsci
  python3-pyqt5.qtserialport python3-sip qttranslations5-l10n
Suggested packages:
  python3-pyqt5-dbg
The following NEW packages will be installed:
  libqt5clucene5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5gui5
  libqt5help5 libqt5network5 libqt5printsupport5 libqt5scintilla2-11
  libqt5scintilla2-l10n libqt5serialport5 libqt5sql5 libqt5sql5-sqlite
  libqt5test5 libqt5widgets5 libqt5xml5 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1
  libxkbcommon-x11-0 python3-pyqt5 python3-pyqt5.qsci
  python3-pyqt5.qtserialport python3-sip qttranslations5-l10n
The following packages will be upgraded:
  mu
1 upgraded, 28 newly installed, 0 to remove and 63 not upgraded.
1 not fully installed or removed.
Need to get 13.5 MB of archives.
After this operation, 52.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by RogueM** [comment]
also, I downloaded a fresh copy of the deb and just to be sure I wasn't going mad here's the output of dpkg-deb --info:

```
pi@raspberrypi:~ $ dpkg-deb --info ./mu-2016-07-29_23_01_16.deb
 new debian package, version 2.0.
 size 686246 bytes: control archive=2210 bytes.
      40 bytes,     1 lines      conffiles
     386 bytes,     9 lines      control
    3896 bytes,    43 lines      md5sums
     152 bytes,     9 lines   *  postinst             #!/bin/sh
     377 bytes,    12 lines   *  prerm                #!/bin/sh
 Package: mu
 Version: 0.1-1
 Architecture: all
 Maintainer: Nicholas Tollervey <ntoll@ntoll.org>
 Installed-Size: 1770
 Depends: python3, python3:any (>= 3.3.2-2~), python3-setuptools, python3-pyqt5, python3-pyqt5.qsci, python3-pyqt5.qtserialport, python3-serial, python3-pep8, pyflakes
 Section: python
 Priority: optional
 Description: A simple editor for kids, teachers and new programmers.
```

so it looks like that package was built with a different control file?

**Comment by RogueM** [comment]
incidentally, looking closer I don't think running `sudo apt-get install -f` after the fact works... I would say it is merely fulfilling the dependencies of the existing mu package in the repo, not that of what I just installed. I suspect it's because they both are tagged with the same exact version, but I am by no means an expert in the matter.

**Comment by RogueM** [comment]
and for reference here is what is currently in the Raspbian repo:

```
pi@raspberrypi:~ $ apt-cache show mu
Package: mu
Version: 0.1-1
Architecture: all
Maintainer: Nicholas Tollervey <ntoll@ntoll.org>
Installed-Size: 1596
Depends: python3, python3:any (>= 3.3.2-2~), python3-pyqt5, python3-pyqt5.qsci, python3-pyqt5.qtserialport
Priority: optional
Section: python
Filename: pool/main/m/mu/mu_0.1-1_all.deb
Size: 620830
SHA256: 63b27cd21dd9e40f379144b3c610055ff92e666b1f6264ed5ee2ff7dafda22f9
SHA1: 56be878bab74c4858ddb0c68d125cea68ceb84d8
MD5sum: a748e4b1d912c5535fef5e94bedf9d7f
Description: A simple editor for kids, teachers and new programmers.
Description-md5: 47bec7f5e3fd19944aef13c305f5ea26
```

**Comment by carlosperate** [comment]
Okay, sorry it took me a little while to reply, there has been quite a few replies, so please remind me if I haven't covered something.

Thanks for the info @bennuttall/@xecdesign, even if the current packages are present it will be good to know what the general procedure for submission is, as there are other packages that will be needed as well for additional features.

@xecdesign what did you mean about `python3-pkg-resources` being missing from the dependencies? I believe it's a dependency for `python3-setuptools` already and included this way, is it not available in raspbian?


As mentioned already, I forgot about the fact that dpkg does not do dependency management like the usual tools installed in other distros (gdebi, ubuntu software centre, etc). So to test the deb package installation properly, on a new raspbian installation it should work by just executing:

```
sudo dpkg -i <mu.deb-file>
sudo apt-get -f install
```

This is mentioned in the [installation instructions file](https://s3-us-west-2.amazonaws.com/ardublockly-builds/microbit/raspberry_pi/installation_instructions.txt) on the list with the [latest builds for the raspberry pi](http://ardublockly-builds.s3-website-us-west-2.amazonaws.com/?prefix=microbit/raspberry_pi/). I know I didn't link this list directly before, but hopefully the type of users downloading these builds would be able to spot this small doc as well.

If the application opens successfully it should be enough proof that all dependencies has been met. There are no hidden/nested imports (they are all at top of the py files), so if it launches it means there was no `ImportError` exception.

About the using python-flake8 package and having also python3-pep8, I had issues with some of these packages on Ubuntu 14.04, which is the earliest Ubuntu version where Mu works without messing with backports. And so, in order to be as compatible as possible this also the version used on the build server.
To be honest I don't remember exactly what the problem was, if I recall correctly installing the pyflakes package on its own with pep8 still gave me import errors. But anyway, to avoid any further confusions (as might linked deb file might have not contain the control file listed in this PR), I have just updated it once more. In this case I went back to adding `python3-pep8` and `pyflakes` (this package installs for python 2 and 3), and after a quick test on 14.04 it should be ready as well for the pi.


https://s3-us-west-2.amazonaws.com/ardublockly-builds/microbit/raspberry_pi/mu-2016-08-18_01_27_58.deb

**Comment by XECDesign** [comment]
@carlosperate You're quite right. I seem to have ended up in a state where mu installed correctly, but setup-tools was not installed after running `apt-get install -f`. I suspect the clash between two mu packages with the same version string confuses apt a bit.

**Comment by XECDesign** [comment]
To submit packages, you can either email them to serge at raspberrypi (dot org) or send your public ssh and package signing keys to use dput instead.

**Comment by RogueM** [comment]
@carlosperate 
```
sudo dpkg -i <mu.deb-file>
sudo apt-get -f install
```
does not work if the package in the repo has the same version tag as the build you are trying to roll. In fact I believe `apt-get -f install` reinstalls the repo version of mu as part of resolving missing dependencies.

**Comment by RogueM** [comment]
this is what happens:

```
pi@raspberrypi:~ $ sudo dpkg -i ./mu-2016-08-18_01_27_58.deb
Selecting previously unselected package mu.
(Reading database ... 118520 files and directories currently installed.)
Preparing to unpack ./mu-2016-08-18_01_27_58.deb ...
Unpacking mu (0.1-1) ...
dpkg: dependency problems prevent configuration of mu:
 mu depends on python3-pep8; however:
  Package python3-pep8 is not installed.
 mu depends on pyflakes; however:
  Package pyflakes is not installed.

dpkg: error processing package mu (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing: mu

pi@raspberrypi:~ $ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  mu
The following packages will be upgraded:
  mu
1 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.
1 not fully installed or removed.
Need to get 0 B/621 kB of archives.
After this operation, 178 kB disk space will be freed.
Do you want to continue? [Y/n] y
Reading changelogs... Done
(Reading database ... 118571 files and directories currently installed.)
Preparing to unpack .../apt/archives/mu_0.1-1_all.deb ...
Unpacking mu (0.1-1) over (0.1-1) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Setting up mu (0.1-1) ...
```
so, yes, what you end up with is not the latest build, but what's in the repo...

**Comment by carlosperate** [comment]
Yes, I guess that does make sense.

Currently the version issue is due to my inexperience generating and automating deb packages, so the CI build server basically generates a bunch of new deb files all with the same version as the latest release. There is a discussion on https://github.com/ntoll/mu/pull/102 with more info as to what it is currently doing. When the new version of Mu gets properly packaged this should not be an issue for users.

@XECDesign if you could have a quick look at https://github.com/ntoll/mu/pull/102#discussion_r60506880 maybe you could spot where I am going wrong with the packaging commands?

**Comment by XECDesign** [comment]
@carlosperate everything looks okay there. Do you have a branch of what you get after running git-dch? If the changelog entry is updated and committed, I don't see how the version would be wrong.

**Comment by carlosperate** [comment]
The CI server builds the deb file on each commit to this repository, so my intention was to not add another consecutive commit just to increase the version number for "unofficial" releases, so the updated file is not committed. It's been a while, but as I mentioned in that comment:

> the --git-ignore-new flag is defined as Don't abort if there are uncommitted changes in the source tree or the current branch doesn't match the DEBIAN-BRANCH., so I'm assuming here it still uses the edited changelog?

So I need that flag because of the change, but it doesn't seem to use it?
Is there a way to create a deb file without adding a new commit?

**Comment by RogueM** [comment]
I think the easiest might be to create an intermediate version that apt will treat as newer than what you have progagated in official repos?

In my view, what you do now _shouldn't_ be a big issue except when the control file, specifically the runtime dependencies, changes? In other words, it might not be worth the hassle to try to cater with that particular corner case?

**Comment by carlosperate** [comment]
I think that could be a good compromise, have an intermediate version so that it doesn't clash with the package in the distro repositories. Does this interim entry have to stay in the history? I assume it will be fine to replace it so that it does not appear in the proper releases history?

@asb , since you are the package maintainer, does this sound good?

**Comment by RogueM** [comment]
I don't think the history in the changelog has any relevance no, but if you want to allow the next release package in the repository to automatically upgrade those you may need to format the version in a specific way.

... I read the debian packaging doc a while back but there's definitely ways to tag a build so it works both ways i.e it is deemed newer than current repo version, but older than the next, without messing up too much your intended version scheme. I'll see if I can find the info back.

**Comment by RogueM** [comment]
here's the bit from the debian policy regarding versions:
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

and dpkg itself can be used to confirm the validity of version comparison ahead of time... for example, you could use ~pre to tag your intermediate builds, like so:
```
dpkg --compare-versions 0.1-1 lt 0.2~pre-1 && echo $?
dpkg --compare-versions 0.2-1 gt 0.2~pre-1 && echo $?
```

**Comment by carlosperate** [comment]
Thanks for the info @RogueM.

If we could build the deb packages without committing the server-edited history I could use the build number issued by the Jenkins as as part of it (in case anybody is interested, currently at around 90 https://twitter.com/tinypici), but that appended tag would not be reset between versions, so it'd go like: `0.2~pre90`, `0.2~pre91`, `0.2`, `0.3~pre92`, etc.

On the other hand, for the current solution of having "interim" history entries between releases, in this case we can still manually increase the version appendix every time the dependencies change (so I'd have to do that in this PR). However I am still wondering if the deb package cares about any history version entry that is not the last.

So say we have `0.1`, `0.2~pre1`, and `0.2`. If a user installs `0.2~pre1` with the following history:

```
mu (0.2-~pre1) unstable; urgency=low
... Interim release... blah blah blah ...

mu (0.1-1) unstable; urgency=low
... Proper release ... blah blah blah ...
````

And then on release, the distro repository (or downloaded) deb file has the `0.2-~pre1` entry missing and instead just:

```
mu (0.2); urgency=low
... Proper release, blah blah blah ...

mu (0.1-1) unstable; urgency=low
... Proper release ... blah blah blah ...
````

Would that cause any problems at all? I'm not a big fan of keeping the "xxx~prex" entries in the history, but don't know if removing them would cause any issues with upgrades.

**Comment by RogueM** [comment]
I think that wouldn't cause any trouble... at least I don't recall reading anything in the official doc that would indicate the changelog matter to anything but the deb build process.

but just to be clear, I am very much inexperienced with debian packaging overall, having only recently contributed tentative such packaging that have yet to be iterated by development, so take my input with a grain of salt.

**Comment by RogueM** [comment]
I found the following q&a which raises the concern superficially:
https://wiki.debian.org/DebianMentorsFaq#Is_it_OK_to_edit_old_changelog_entries.3F

... the linked discussion seems to be about the appropriateness of doing so, not from a technical pov but that of motivation and clarity... since you don't intend to spread those ~pre to official repos I see even less reasons to concern yourself about it if there's indeed no technical hurdle to suppress or otherwise amend the changelog retroactively, as that whole discussion seem to imply.

I hope this helps though I realise it does not cover the case of a release entry disappearing entirely, but the more I read the less I think there is any technical relevance to the changelog during upgrade, besides version comparison of the top entry.

**Comment by carlosperate** [comment]
Thanks for the info @RogueM, sounds like there is no tech problems in removing "interim" entries other than the fact that modifying the changelog goes against its philosophy.

Personally I think it would be okay in this case since these builds are not meant for general public consumption, and for the proper releases their changelog would actually stay intact.

**Comment by ntoll** [comment]
Everyone! Wow, what an epic PR and many thanks for all your input!

Just (finally) finding time to go through the pending PR's.

I believe this is safe to merge (after reading the sterling efforts in the comments above). However, since I know *nothing* about Debian packaging I won't click the "Merge" button until @carlosperate confirms this with a "make it so" comment in a commanding Jean-Luc Picard sort of a way on this thread. ;-)

**Comment by carlosperate** [comment]
At the current state this PR is good to merge, although probably not complete. It fixes the dependencies for any new installs, but might not do so for systems with version 0.1 already installed (mostly raspberry pi users). This is not really an issue when doing a proper release to go into the distro repositories, as the log has to be manually edited anyway at that point. I'll open a new issue to investigate the use of "interim" entries in the history log for these CI built "in-between releases" deb files. 

So... :D
make it so

**Comment by ntoll** [comment]
giphy

**Pull request merged**
