### PR TITLE
Decoupled

### PR DESCRIPTION
**Pull request by ntoll**
This branch stacks on Al's great work on decoupling the logic from the UI code. I've taken that, run with it and we have a more-or-less feature complete editor.

Todo:

* Tests
* Docs
* Tests
* Tests
* Docs

:-)

### CODE REVIEW

**Comment by carlosperate** [comment]
Getting the following error on Windows:

```
(mu3) E:\workspaces\git\mu>py -3 run.py
Qt: Untested Windows version 10.0 detected!
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from mu.app import run
  File "E:\workspaces\git\mu\mu\app.py", line 24, in <module>
    from mu.editor import Editor
  File "E:\workspaces\git\mu\mu\editor.py", line 35, in <module>
    os.mkdir(DATA_DIR)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Carlos\\AppData\\Local\\python\\mu'
```

**Comment by ntoll** [comment]
Hi @carlosperate can you create a separate bug report for this please? I think I know what the problem may be. Can you confirm how deep the specified path is correct..? (E.g. it's probably good up to C:\\Users\\Carlos\\AppData\\Local). PR's welcome. ;-)

**Comment by carlosperate** [comment]
@ntoll, yes I was looking into it right now, I'll create a new issue.

**Comment by ntoll** [comment]
Great stuff and, as always, many many thanks. :-)

**Comment by carlosperate** [comment]
np! reported in issue https://github.com/ntoll/mu/issues/49

**Pull request merged**
