### PR TITLE
Fix OSX packaging

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by carlosperate** [comment]
LGTM so far, but we haven't been able to check the latest built executable, right?

**Comment by inglesp** [comment]
No, we haven't, but I'm inclined to merge anyway and hope for the best, since we're not going to break anything by doing so.

**Comment by ntoll** [comment]
It doesn't work... I just tried it on Mary's Mac and I get:

```
ImportError: No module named 'PyQt5.Qsci'
```

Sooooooo close... ;-)

**Comment by inglesp** [comment]
@ntoll, where are you downloading the image from?  As far as I can see, there's only images built from master at http://ardublockly-builds.s3-website-us-west-2.amazonaws.com/?prefix=microbit/osx/.

**Comment by ntoll** [comment]
damn... my mistake, I was getting over excited and lost that part of the context (i.e. pushing assets to AWS for all branches).

**Comment by ntoll** [comment]
I'll merge so we can see... ;-)

**Comment by carlosperate** [comment]
It works! Fantastic work @inglesp !

**Comment by inglesp** [comment]
Hurrah!

**Pull request merged**
