### PR TITLE
Try to understand why OSX package doesn't run

### PR DESCRIPTION
**Pull request by inglesp**
Don't merge me!!!

### CODE REVIEW

**Comment by inglesp** [comment]
The problem I'm trying to understand is that when I run the OSX executable that Travis builds, we get the following error:

```
$ ./mu-2016-01-12_09_22_21 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "mu/app.py", line 23, in <module>
ImportError: No module named PyQt5.QtWidgets
run returned -1
```

The debugging output that I've added demonstrates that after homebrew has installed the necessary Qt libraries, Travis is able to import `PyQt5.QtWidgets`, which suggests that PyInstaller's not able to find it -- so I've just tweaked the PyInstaller code we're using to log verbosely, and I'll look at the output tomorrow.

**Comment by inglesp** [comment]
Also, the reason for the failure of b4e96c3 is that the build timed out -- the slowness is caused by homebrew thinking it has to install pyqt5 twice.  :-1:

**Comment by inglesp** [comment]
So the build now runs much more quickly (hurrah!) but the verbose logging produces too many logs, so the build job gets terminated (boo!).

**Comment by ntoll** [comment]
That's progress... I'm currently building a test suite..! 45% test coverage so far this evening. It'll be wonderful when it's done! ;-)

**Comment by carlosperate** [comment]
Don't forget to change the travis deployment to all branches, or the built file will not be uploaded.
Based on the latest run it looks like pyinstaller has added more modules to the file, as it is about 17Mbs now: https://travis-ci.org/ntoll/mu/jobs/102198080#L276
That's a similar size to the first osx test, so there is a chance that it could still have the QSCI module missing.

**Comment by inglesp** [comment]
Hey @carlosperate -- how would I change the travis deployment to all branches?

**Comment by carlosperate** [comment]
I believe you'd have to change line 55 from `branch: [master, travis]` to `all_branches: true`. More info in: https://docs.travis-ci.com/user/deployment/

**Comment by inglesp** [comment]
Closing in favour of https://github.com/ntoll/mu/pull/60.

**Comment by inglesp** [comment]
Thanks @carlosperate -- I think in this case, I'd rather just get #60 merged.  Would you like to review it?

**Pull request closed without merging**
